name: someone fork repo ci
on:
  watch:
    types: started
jobs:
  pushdeer:
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://api2.pushdeer.com/message/push?pushkey=PDU12980TRBFWQ4ieHk97sbf4EDrgFsUpxhUypyWd&text=${{ github.repository }}有小可爱Star啦！"
