name: someone fork repo ci
on:
  watch:
    types: started
jobs:
  pushdeer:
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://api2.pushdeer.com/message/push?pushkey=${{ secrets.pushdeer_key }}&text=${{ github.repository }}有小可爱Star啦！"
